[package]
name = "symsorter"
version = "0.3.4"
authors = ["Sentry <hello@getsentry.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
chrono = { version = "0.4.19", features = ["serde"] }
console = "0.14.0"
lazy_static = "1.4.0"
object = { path = "../../../object", features = ["write_core"] }
rayon = "1.5.0"
regex = "1.4.3"
serde = { version = "1.0.119", features = ["derive"] }
serde_json = "1.0.61"
structopt = "0.3.21"
# This is locally checked out to fix/demangle-fixes to match what's being used on `master`
symbolic = { path = "../../../symbolic/symbolic", features = ["debuginfo-serde"] }
walkdir = "2.3.1"
zip = "0.5.11"
zstd = "0.6.0"
